#!/bin/sh
#
# This shell script if placed in /etc/apcupsd
# will be called by /etc/apcupsd/apccontrol when apcupsd
# detects that the battery should be replaced.
# We send an email message to root to notify him.
#

HOSTNAME=`hostname`
NOTIFY_HOST="ntfy.sh"
NOTIFY_TOPIC=your-own-topic

haveCurl=$(which curl)

if [ $? -ne 0 ]; then
  echo "Curl is not installed or not found in path, please install curl."
  exit 1
fi

curl \
  -s \
  -o /dev/null \
  -H "Title: $HOSTNAME UPS $1 Battery Needs Replaced" \
  -H "Priority: urgent" \
  -H "Tags: ups,skull,battery" \
  -d "$HOSTNAME UPS $1 battery requires replacement!" $NOTIFY_HOST/$NOTIFY_TOPIC

exit 0
